#!/bin/bash

################################
### DO NOT EDIT THIS FILE DIRECTLY, INSTEAD, COPY TO YOUR LOCAL ~/script directory and edit there
### $ mkdir ~/script
### $ cp scripts/<THIS_FILENAME> ~/script/
### $ cd ~/script/
### EDIT FILE
### $ ./<THIS_FILENAME>
################################

# fail if any commands fails
set -e
# debug log
#set -x

############ Script

read -rp "Configure VPN access?: (y|n)" configureVpnAccess
read -rp "Install Idaptive mobile application?: (y|n)" installIdaptiveMobileApplication
read -rp "Connect to Cisco AnyConnect VPN?: (y|n)" connectToAnyconnectVpn
read -rp "Create a new SSH key? : (auto|manual|no)" generateSshKey
read -rp "Clone automation repositories? : (y|n)" cloneRepos
read -rp "Clone Flow Factory repositories? : (y|n)" cloneReposFlowFactory

# Clone company repositories
echo "Cloning company repositories..."

if [ "$configureVpnAccess" = "y" ]; then
  echo "installing packages..."
  brew install -q openconnect
  echo "installing packages... DONE"
  echo "Creating user aliases... "
  #read -rp "Enter Juniper Boromir VPN username: " juniperUsername
  #read -rp "Enter Juniper Boromir VPN password: " juniperPassword
  ##read -rp "Enter Juniper Boromir VPN servercert: " juniperServercert
  #echo "${juniperPassword}" > ~/.ocvpn_secret
  #echo "alias openconnect_juniper='cat ~/.ocvpn_secret | sudo /usr/bin/openconnect --juniper boromir.fibertel.com.ar --servercert sha256:sha256cert --user=${juniperUsername} --passwd-on-stdin'" >>~/.zshrc
  read -rp "Enter Cisco AnyConnect VPN username (uXXXXXX): " openconnectUsername
  echo "alias openconnect_anyconnect='sudo openconnect -u ${openconnectUsername} vpn-ssl.telecom.com.ar'" >>~/.zshrc
  source ~/.zshrc
  echo "Creating user aliases... DONE"
  echo "Download and install Cisco AnyConnect Mobility Client from"
  echo "  http://dl.nextadmin.net/dl/Cisco%20AnyConnect%20Secure%20Mobility%20Client/"
  read -p "Press enter to continue"
fi

if [ "$installIdaptiveMobileApplication" = "y" ]; then
  echo "Connect to anyConnect VPN"
  echo "  In a smartphone, search and install 'Idaptive' application from Play Store"
  echo "    https://play.google.com/store/apps/details?id=com.centrify.mdm.samsung"
  echo "  If using a smartphone without google play or google services do:"
  echo "    1) Download and install 'F-Droid' from https://f-droid.org/F-Droid.apk"
  echo "    2) Install 'Aurora Store' from F-Droid"
  echo "    3) Install 'Idaptive' from Aurora Store"
  echo ""
  read -p "Press enter to continue"
  echo "Idaptive mobile application steps:"
  echo "  1) Open 'Idaptive' mobile application"
  echo "  2) Login using \"uXXXXXX@telecom\" (don't put 'uXXXXXX@teco.com.ar') and \"LAN password\"."
  echo "  3) Don't wait for apps to load (It won't). Go to menu and select \"Mobile Authenticator\"."
  echo "  4) Use temporary token to connect to VPN."
  read -p "Press enter to continue"
fi

if [ "$connectToAnyconnectVpn" = "y" ]; then
  echo "Connecting to Cisco AnyConnect VPN..."
  echo "Open a new terminal and do the following..."
  echo "    $ openconnect_anyconnect"
  echo "    or..."
  echo "    $ sudo openconnect -u ${openconnectUsername} vpn-ssl.telecom.com.ar"
  echo "  When asking for password enter your 'LAN password'"
  echo "  When asking for password again, enter the Idaptive temporary token password"
  echo ""
  echo -e "\033[33;5m PLEASE NOTE THAT BOTH PASSWORD PROMPTS LOOK THE SAME! \033[0m"
  echo ""
  echo "    or..."
  echo "Open Cisco AnyConnect Mobility Client GUI from Applications/cisco/ directory"
  echo "  Connect to vpn-ssl.telecom.com.ar"
  read -p "Press enter to continue"
  echo "Connecting to Cisco AnyConnect VPN... DONE"
fi

if [ "$generateSshKey" = "auto" ] || [ "$generateSshKey" = "manual" ]; then
  echo "Create or access Gitlab account:"
  echo "  1) Open http://10.200.172.71 in a web browser."
  echo "  2) Access with your gitlab credentials or create a new one."
  echo ""
  echo "  Warning! Don't close Gitlab page when finished..."
  echo ""
  read -rp "Press enter when finish to create ssh keys..."
fi

if [ "$generateSshKey" = "manual" ]; then
  echo "Open a new terminal and do the following..."
  echo "You should generate ssh keys with command:"
  echo "  $ ssh-keygen"
  echo "  note: when asked for a file location and for a passphrase,"
  echo "        just press enter key for defaults and blank passphrase."
  echo ""
  echo "Now, copy the contents of the file ~/.ssh/id_rsa.pub to the clipboard,"
  echo "with the command:"
  echo "  $ xclip -sel c < ~/.ssh/id_rsa.pub"
  echo ""
  read -rp "Press enter when finish to continue..."
fi

if [ $generateSshKeyAuto = "y" ]; then
  echo "Generating ssh key in ~/.ssh/id_rsa.pub file..."
  cat /dev/zero | ssh-keygen -q -N ""
  echo "Generating ssh key in ~/.ssh/id_rsa.pub file... DONE"
  echo "Copy '~/.ssh/id_rsa.pub' content to the clipboard..."
  cat ~/.ssh/id_rsa.pub
  read -p "Press enter when finish to continue"
  echo "Copy '~/.ssh/id_rsa.pub' content to the clipboard... DONE"
fi

if [ "$generateSshKey" = "auto" ]; then
  echo "Generating ssh key in ~/.ssh/id_rsa.pub file..."
  cat /dev/zero | ssh-keygen -q -N ""
  echo "Generating ssh key in ~/.ssh/id_rsa.pub file... DONE"
  echo "Copy '~/.ssh/id_rsa.pub' content to the clipboard..."
  cat ~/.ssh/id_rsa.pub
  read -p "Press enter when finish to continue"
  echo "Copy '~/.ssh/id_rsa.pub' content to the clipboard... DONE"
fi

if [ "$generateSshKey" = "auto" ] || [ "$generateSshKey" = "manual" ]; then
  echo "Add SSH keys to Gitlab account:"
  echo "  1) Access ssh-keys settings in http://10.200.172.71/profile/keys"
  echo "  2) Paste the key copied from ~/.ssh/id_rsa.pub and press 'Add key' button."
  echo ""
  read -rp "Press enter when finish to continue..."
fi

if [ $cloneRepos = "y" ]; then
  echo "Creating ~/repos directory..."
  mkdir -p ~/repos
  echo "Creating ~/repos directory... DONE"
  echo "Cloning automation repos..."
  cd ~/repos || return
  git clone -b develop git@10.200.172.71:Automation/automation-wiki.git
  git clone -b develop git@10.200.172.71:Automation/automation-tools.git
  git clone -b develop git@10.200.172.71:Automation/automation-minerva.git
  git clone -b develop git@10.200.172.71:Automation/automation-gateway.git
  git clone -b develop git@10.200.172.71:Automation/automation-webclient.git
  git clone -b develop git@10.200.172.71:Automation/automation-webclient-analytics.git
  git clone -b develop git@10.200.172.71:Automation/automation-smarttv-ff.git
  git clone -b develop git@10.200.172.71:Automation/automation-android.git
  git clone -b develop git@10.200.172.71:Automation/automation-android-tv.git
  git clone -b develop git@10.200.172.71:Automation/automation-ios.git
  git clone -b develop git@10.200.172.71:Automation/automation-jmeter.git
  git clone -b develop git@10.200.172.71:Automation/automation-wrk.git
  git clone -b develop git@10.200.172.71:Automation/automation-api-iot.git
  git clone -b develop git@10.200.172.71:Automation/automation-web-iot.git
  git clone -b develop git@10.200.172.71:Automation/automation-android-iot.git
  git clone -b develop git@10.200.172.71:Automation/automation-ios-iot.git
  echo "Cloning automation repos... DONE"
fi

if [ "$cloneReposFlowFactory" = "y" ]; then
  echo "Creating ~/repos directory..."
  mkdir -p ~/repos
  echo "Creating ~/repos directory... DONE"
  echo "Cloning Flow Factory repos..."
  cd ~/repos || return
  git clone -b develop git@bitbucket.org:tecoflowfactory/flow-android.git
  git clone -b develop git@bitbucket.org:tecoflowfactory/flow-android-tv.git
  git clone -b releases git@bitbucket.org:tecoflowfactory/flow-android-core-library.git
  git clone -b develop git@bitbucket.org:tecoflowfactory/flow-smart-tv.git
  git clone -b develop git@bitbucket.org:tecoflowfactory/webclient.git
  git clone -b develop git@bitbucket.org:tecoflowfactory/ios.git
  git clone -b develop git@bitbucket.org:tecoflowfactory/flow-iot.git
  git clone -b develop git@bitbucket.org:tecoflowfactory/iot-web.git
  echo "Cloning Flow Factory repos... DONE"
fi

echo "Cloning company repositories... DONE"
