#!/bin/bash

################################
### DO NOT EDIT THIS FILE DIRECTLY, INSTEAD, COPY TO YOUR LOCAL ~/script directory and edit there
### $ mkdir ~/script
### $ cp scripts/<THIS_FILENAME> ~/script/
### $ cd ~/script/
### EDIT FILE
### $ ./<THIS_FILENAME>
################################

# fail if any commands fails
set -e
# debug log
#set -x

############ Script

read -rp "Set Java default version to openjdk 11?: (y|n)" setJavaDefault
read -rp "Configure Git user options?: (y|n)" configureGit
read -rp "Update Clamav virus definitions?: (y|n)" updateClamavVirusDefinitions
read -rp "Create user bin directory?: (y|n)" createUserBinDirectory
read -rp "Configure Docker?: (y|n)" configureDocker

### Configure applications
echo "Configuring applications..."

# Configure Java
if [ "$setJavaDefault" = "y" ]; then
  echo "Setting JAVA HOME..."
  export JAVA_HOME=$(/usr/libexec/java_home -v11)
  export PATH=$JAVA_HOME/bin:$PATH
  echo "Setting JAVA HOME... DONE"
fi

# Configure GIT
if [ "$configureGit" = "y" ]; then
  echo "Configuring Git options..."
  read -rp "Enter Git user email: " gitUserEmail
  git config --global user.email "$gitUserEmail"
  read -rp "Enter Git user name: " gitUserName
  git config --global user.name "$gitUserName"
  git config --global pull.rebase false
  echo "Configuring Git options... DONE"
fi

# Start docker
if [ "$configureDocker" = "y" ]; then
  echo "Open Docker from Finder > Applications and start Docker daemon..."
  echo "  Also, in 'Preferences' > 'Resources' > 'Memory' set needed Memory amount"
  echo "  (Selenium jobs limit is between 4Gb and 6Gb each)"
  read -p "Press enter to continue"
  echo "Open Docker from Finder > Applications and start Docker daemon... DONE"
fi

# update clamav definition database
if [ "$updateClamavVirusDefinitions" = "y" ]; then
  echo "Updating clamav virus definition database..."
  cp /usr/local/etc/clamav/freshclam.conf.sample /usr/local/etc/clamav/freshclam.conf
  sed -i '' 's/Example/#Example/g' /usr/local/etc/clamav/freshclam.conf
  freshclam
  echo "Updating clamav virus definition database... Done"
fi

# home bin directory
if [ "$createUserBinDirectory" = "y" ]; then
  echo "Creating user 'bin' directory..."
  cd || return
  mkdir -p ~/bin
  echo "PATH=\$PATH:~/bin/" >>~/.profile
  source ~/.profile
  echo "Creating user 'bin' directory... DONE"
fi

echo "Configuring applications... DONE"