#!/bin/sh

ram=$(top -b -n 1 | grep "MiB Mem" | awk {'print $6'})
distro=$(cat /etc/issue | awk '{print $1}')
if [ $distro = 'Arch' ]; then
    disk=$(df -h 2>/dev/null | grep "/dev/mapper/root" | awk {'print $4'})
elif [ $distro = 'Devuan' ]; then
    disk=$(df -h 2>/dev/null | grep "/dev/mapper/devuan--vg-home" | awk {'print $4'})
fi
batt=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep 'percentage' | awk '{print $2}')
date=$(date '+%Y-%m-%d %H:%M')
echo "D:$disk R:$ram B:$batt | $date"
