#!/bin/sh

ram=$(top -b -n 1 | grep "MiB Mem" | awk {'print $6'})
disk=$(df -h 2>/dev/null | grep "/dev/nvme0n1p2" | awk {'print $4'})
cpu_temp=$(sensors | grep "Core 0:" | awk {'print $3'})
batt=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep 'percentage' | awk '{print $2}')
date=$(date '+%Y-%m-%d %H:%M')
echo "T:$cpu_temp D:$disk R:$ram B:$batt | $date"
