#!/bin/sh

while true; do
        RAM=$(top -b -n 1 | grep "MiB Mem" | awk {'print $6'})
        DISK=$(df -h | grep "/dev/mapper/root" | awk {'print $4'})
        DATE=$(date '+%Y-%m-%d %H:%M')
        AMIXER=$(amixer sget Master | grep "Front Left:" | awk {'print $5'} | tr -d "[" | tr -d "]")
        NWBSSID=$(nmcli device wifi | grep "*" | awk {'print $3'})
        NWSIGNAL=$(nmcli device wifi | grep "*" | awk {'print $9'})
        echo -en "  net: $NWBSSID $NWSIGNAL | disk: $DISK ram: $RAM | vol: $AMIXER | $DATE\r"
        sleep 30
done
