#!/bin/ksh

RAM=$(top -b -n 1 | grep "Memory: " | awk {'print $6'})
disk=$(df -h /home 2>/dev/null | grep '\/home$' | awk {'print $4'})
DATE=$(date '+%Y-%m-%d %H:%M')
AMIXER=$(amixer sget Master | grep "Front Left:" | awk {'print $5'} | tr -d "[" | tr -d "]")
NWBSSID=$(nmcli device wifi | grep "*" | awk {'print $3'})
NWSIGNAL=$(nmcli device wifi | grep "*" | awk {'print $9'})
echo -en "net: $NWBSSID $NWSIGNAL | disk: $DISK ram: $RAM | vol: $AMIXER | $DATE"
