#!/bin/bash

################################
### DO NOT EDIT THIS FILE DIRECTLY, INSTEAD, COPY TO YOUR LOCAL ~/script directory and edit there
### $ mkdir ~/script
### $ cp scripts/<THIS_FILENAME> ~/script/
### $ cd ~/script/
### EDIT FILE
### $ ./<THIS_FILENAME>
################################

# fail if any commands fails
set -e
# debug log
#set -x

### Configuration ###
### set USAGE message
MESSAGE="USAGE: macosAppiumUpdateWebdriverAgent.sh <deviceID|459afad8c67332fb74b3f68d39210567d391af7c>"
if [ -z "$1" ]; then
    echo $MESSAGE
    echo "  Available devices:"
    xcrun xctrace list devices
    exit 1
fi
DEVICEID=$1
echo "Setting deviceID to $DEVICEID"

# Local configuration
APPIUM_WEBDRIVERAGENT_WORKING_DIR=/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent

echo "Access $APPIUM_WEBDRIVERAGENT_WORKING_DIR directory..."
cd $APPIUM_WEBDRIVERAGENT_WORKING_DIR
echo "Access $APPIUM_WEBDRIVERAGENT_WORKING_DIR directory... DONE"

open WebDriverAgent.xcodeproj
echo ""
echo "###############################"
echo "## Manual intervention required"
echo "###############################"
echo ""
echo "1)Open 'WebDriverAgent' > 'WebDriverAgentLib' and then 'Signing & Capabilities'"
echo "2)In 'Team' select a new one"
echo "3)Add developer account for appleId"
echo "  productocablevision@gmail.com,Desarrollo19"
echo "4)Select Team 'Telecom Personal'"
echo "5)Change 'Bundle identifier' to"
echo "  flow.appium-ios"
read -p "Press enter key after following the steps"
echo ""

echo "6)Open 'WebDriverAgent' > 'WebDriverAgentRunner' and then 'Signing & Capabilities'"
echo "7)Select Team 'Telecom Personal'"
echo "8)Change in 'Build settings' > 'Product Bundle identifier' to"
echo "  flow.appium-ios"
read -p "Press enter key after following the steps"
echo ""

echo "9)Open 'WebDriverAgent' > 'IntegrationApp' and then 'Signing & Capabilities'"
echo "10)Select Team 'Telecom Personal'"
echo "11)Change 'Bundle identifie' to"
echo "  flow.appium-ios"
read -p "Press enter key after following the steps"
echo ""

echo "12)Close xcode"
read -p "Press enter key after following the steps"

echo "Deleting ~/Library/Developer/Xcode/DerivedData/ directory..."
rm -rf ~/Library/Developer/Xcode/DerivedData/
echo "Deleting ~/Library/Developer/Xcode/DerivedData/ directory... DONE"

echo "Deleting Carthage/ directory ..."
rm -rf Carthage/
echo "Deleting Carthage/ directory... DONE"

echo "Running 'Scripts/bootstrap.sh -d' command..."
FILE=${APPIUM_WEBDRIVERAGENT_WORKING_DIR}/Scripts/bootstrap.sh
if [ -f "$FILE" ]; then
    sh $FILE -d
else
    echo "$FILE does not exist."
fi
echo "Running 'Scripts/bootstrap.sh -d' command... DONE"

echo "Compiling 'WebDriverAgentRunner' to device '${DEVICEID}'..."
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination "id=${DEVICEID}"
echo "Compiling 'WebDriverAgentRunner' to device '${DEVICEID}'... DONE"